### ISSUE TITLE
New install, blank pages

### ISSUE THREAD

**Issue by singularitytrav** [mmmaly/OpenSourceBikeShare#61]
I have a somewhat confounding issue on a new install of OSBS. I'm on Ubuntu 14.10 with a fresh, up to date LAMP install. I cloned OSBS into /var/www, chown'd to www-data. But the pages are blank and I'm getting an unexpected end of file error in the apache logs. Any ideas?

Below is some diagnostic info:

Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 setenvif_module (shared)
 status_module (shared)

<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

this is just showing we are on the latest version:

commit a89f01df5d041c5f7ea11f893df067a20653c876
Author: Michal Maly <mmmaly+gitmail@gmail.com>
Date:   Thu Mar 12 15:30:30 2015 +0100

    command free - small bugfix

Apache error log:

[Mon Mar 23 23:47:32.428030 2015] [:error] [pid 19078] [client 64.71.25.234:59621] PHP Parse error:  syntax error, unexpected end of file in /var/www/html/OpenSourceBikeShare/install/index.php on line 444

**Comment by nekromoff** [comment]
That's weird. Can you try commenting the purifier lines 7-14 out?

Can you also change the debug info of Apache to higher level? Alas, that one error line is not particularly helpful. Thanks.
