### ISSUE TITLE
old code recovery in web app

### ISSUE THREAD

**Issue by malymichal** [mmmaly/OpenSourceBikeShare#63]
If the user switches the web application immediately after renting a bike (because of a sudden call, mistake, etc.) , the web interface will not show the old code after return (page refresh). 

If the user did not manage to remember the code, s/he does not have any option of old code recovery.

Suggestion: Show the old code in small font.

**Comment by nekromoff** [comment]
Isn't that a possibly security issue to keep showing the old code?

**Comment by malymichal** [comment]
I don't think so. There is no use of the old code except for opening the lock, and that is the intended purpose anyway.
