### ISSUE TITLE
non-unicode characters (typical for Slovak) in note cause error

### ISSUE THREAD

**Issue by NetroSK** [mmmaly/OpenSourceBikeShare#67]
non-unicode characters (typical for Slovak) in note cause error:

e.g.
return 11 virtual Nedá sa na tom jazdiť, treba zväčšiť predne koliesko pod reťazou, hrozne zlý prevod to ma. presunul som ho na ARCHITEKTI na vedlajsi stojan

error (sent 3 times):
Error. The command [CONCAT=-40,3,1]RETURN does not exist. If you need help, send: HELP

**Comment by nekromoff** [comment]
@mmmaly contact API gateway about that, it's their issue again, they should finally support UTF8 fully. other API gateways support it.

e.g. http://api.textmagic.com/https-api "The text-message parameters should be encoded in the UTF-8 character set."
