### ISSUE TITLE
coupon redeem not working

### ISSUE THREAD

**Issue by NetroSK** [mmmaly/OpenSourceBikeShare#69]
I generated 3 eur coupons, marked it as sold in admi. but when trying to redeem, it didnt work. nothing happened when I pressed the green + nor blue + button. no error mrssage.

**Comment by nekromoff** [comment]
more specs or invalid and closed

**Comment by NetroSK** [comment]
just tested it again from desktop and it worked.
from mobile it doesn't work. the problem is in the blue "+" button which should apply the coupon

expected use:
- admin generates promo codes (coupons) for users
- admin gives coupons to users
- admin marks coupons that were just given to users as sold (not to give it again to someone else)
- user redeems the coupon in application by clicking green "+" button, typing the coupon and clicking the blue "+" button

**Comment by nekromoff** [comment]
refresh cache, it works in android browser without a glitch
