### ISSUE TITLE
REVERT doesn't work as desired

### ISSUE THREAD

**Issue by NetroSK** [mmmaly/OpenSourceBikeShare#70]
Bike e.g. 57 was on stand A. Later it was rented by user X and moved to stand B. Later it was rented from stand B. At the moment is rented by user Y. This situation will cause the the command REVERT to return the bike 57 to stand A, instead to stand B.
I think there is and issue because the comment REVERT doesn't consider renting a bike as new bike location.

**Comment by nekromoff** [comment]
couldn't replicate during simple testing, code doublechecked, added forcerent and forcereturn as actions that affect revert

**Comment by NetroSK** [comment]
ok, i will try again, thx
