### ISSUE TITLE
How to move cycles from one stand to another stand.

### ISSUE THREAD

**Issue by Medanaresh** [mmmaly/OpenSourceBikeShare#83]
Is there any option for admin to move cycles from one stand to another, adding extra cycles to a stand. 
And one more doubt about privileges. Is there any meaning for privileges from 1 to  7

**Comment by nekromoff** [comment]
you need to move bicycles from one stand to another not only virtually, but physically too as the locks combination changes. so your option is to rent/return them. there is planned bulk rent/return option.
