### ISSUE TITLE
how to add another station

### ISSUE THREAD

**Issue by Medanaresh** [mmmaly/OpenSourceBikeShare#84]
Hi, thanks for your quick response to my previous question, Is there any option for admin to setup another stand, once the system is running with some stands and bikes, and also  adding more cycles..

**Comment by nekromoff** [comment]
Hello, currently only via direct access to database (e.g. adding a new
record) for both stands and bicycles, but this is planned feature. I
recommend adding all stands including future planned stands during
installation and then marking some of them as disabled (they won't be shown
on a map, serviceTag=1).

Also, generate as many bicycles as you need and put the ones that you don't
have in real world (planned numbers) to a stand that is disabled. These
bicycles then won't be shown either.

Both as temporary measures. Once we have the rewrite done, these will be
new features to be added.

**Comment by Medanaresh** [comment]
Thank you very much for your response,. How to delete the bike notes,  is there any options for admin or user to delete the notes.

**Comment by nekromoff** [comment]
Currently via SMS only:
DELNOTE bikeno [pattern]
where [pattern] could be any text of the note you want to delete, e.g.
Note: bicycle seat broken, needs replacement
DELNOTE bikeno broken
DELNOTE bikeno needs
DELNOTE bikeno bicycle seat broken, needs replacement

all will delete the note.

Alternatively you can delete the note via direct db access, updating
deleted = current time.

**Comment by Medanaresh** [comment]
hi, sorry to disturb you frequently. For new user registration it is possible to store their photo, i tired with php but i get errors, if you suggest me what is the procedure for storing user photo.

**Comment by nekromoff** [comment]
currently, there is no user photo stored, add this as an issue request for
future versions
