### ISSUE TITLE
About sms system

### ISSUE THREAD

**Issue by Medanaresh** [mmmaly/OpenSourceBikeShare#89]
Hi, In config file you are said, loopback is used for dummy otp, how it  is worked. I selected the loop back option, but at the time of registration, i got the error like this , Problem with the SMS code entered. Please check and try again. Please tell me how to solve the issue

**Comment by nekromoff** [comment]
set "loopback" for connect to be used, then navigate to your installation/connectors/loopback/phone.php
optionally, check loopback.log in the same directory for history of SMS received.
